title: "自作のHTML拡張言語「NTML」をVSCodeの拡張機能として作った話"
summary: "VScode拡張機能の開発や、拡張言語開発の初心者向け解説"
topics: ["html", "css", "JavaScript" , "Python" , "" ] # トピック（5つまで）
published: false # falseだと下書き
price: 0 # 有料の場合200〜5000
chapters:
  - example1 # チャプター1