title: "一緒に勉強していこうって本"
summary: "プログラマー志望の高校生が勉強したことを自分の備忘録としてまとめるだけ"
topics: ["html", "css", "JavaScript" , "Python" , "" ] # トピック（5つまで）
published: true # falseだと下書き
price: 0 # 有料の場合200〜5000
chapters:
  - example1 # チャプター1